name: Cypress Automation Tests

on:
  workflow_dispatch:

jobs:
  job1:
    name: cypress-run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packages
        run: npm install

      - name: Run Tests
        run: npx cypress run --env allure=true --spec $(node cypress-parallel.js ${{ matrix.containers }} 2)

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ReportsData-${{ matrix.containers }}
          path: allure-results

  job2:
    name: reports
    if: always()
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results
      
      - name: List downloaded artifacts
        run: |
          echo "Artifact folders:"
          ls -lh allure-results
          echo "ReportsData-0 contents:"
          ls -lh allure-results/ReportsData-0 || echo "Missing ReportsData-0"
          echo "ReportsData-1 contents:"
          ls -lh allure-results/ReportsData-1 || echo "Missing ReportsData-1"
      
      - name: Merge Allure Results from all machines
        run: |
            mkdir -p merged-allure-results
            for folder in allure-results/ReportsData-*; do
              if [ -d "$folder" ]; then
                echo "Merging from $folder"
                rsync -a "$folder"/ merged-allure-results/
              fi
            done
            echo "Final merged contents:"
            ls -lh merged-allure-results
        
      - name: Install Allure CLI
        run: |
            sudo apt-get update
            sudo apt-get install -y default-jre rsync
            curl -o allure-2.27.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
            tar -zxvf allure-2.27.0.tgz
            sudo mv allure-2.27.0 /opt/allure
            sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        
      - name: Generate Allure Report
        run: |
            rm -rf allure-history
            allure generate merged-allure-results --clean -o allure-history
        
      - name: Debug generated report
        run: |
            echo "Generated report contents:"
            ls -lh allure-history
        
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
        