name: Cypress Automation Tests

on:
  workflow_dispatch:

jobs:
  job1:
    name: cypress-run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packages
        run: npm install

      - name: Run Tests
        run: npx cypress run --env allure=true --spec $(node cypress-parallel.js ${{ matrix.containers }} 2)

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ReportsData-${{ matrix.containers }}
          path: allure-results

  job2:
    name: reports
    if: always()
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results
      
      - name: list downloaded files
        run: ls -R allure-results || echo "No artifacts found"
      
      - name: Merge Allure Results from all machines
        run: |
          mkdir -p merged-allure-results
          for dir in allure-results/*; do
            if [ -d "$dir" ]; then
              echo "Merging from $dir"
              cp -r "$dir"/* merged-allure-results/ || true
            fi
          done
      
      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          curl -o allure-2.27.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
      
      - name: Generate Allure Report
        run: |
          allure generate merged-allure-results --clean -o allure-history
      
      - name: Debug allure-history contents
        run: ls -R allure-history || echo "No generated history"
      
      - name: Ensure allure-history exists
        run: mkdir -p allure-history
      
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
      