name: Cypress Automation Tests

on:
  workflow_dispatch:

jobs:
  job1:
    name: cypress-run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Packages
        run: npm install

      - name: Run Tests
        run: npx cypress run --env allure=true --spec $(node cypress-parallel.js ${{ matrix.containers }} 2)

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ReportsData-${{ matrix.containers }}
          path: allure-results

  job2:
    name: reports
    if: always()
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results
      
      - name: list downloaded files
        run: ls -R allure-results || echo "No artifacts found"
      
      - name: Merge Allure Results
        run: |
          mkdir -p merged-allure-results
          cp -r allure-results/ReportsData-*/. merged-allure-results/
      
      - name: Allure Report Action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: merged-allure-results
          allure_history: allure-history
          keep_reports: 20      

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: merged-allure-results
